/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class JNI_HelloWorld */

#ifndef _Included_JNI_HelloWorld
#define _Included_JNI_HelloWorld
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     JNI_HelloWorld
 * Method:    sayHelloWorld
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_JNI_1HelloWorld_sayHelloWorld
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
